# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20150810_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='datePublished',
            field=models.DateField(default=datetime.datetime(2015, 12, 26, 19, 46, 31, 764983, tzinfo=utc)),
        ),
    ]
